# Thresholds and labels for verdict mapping
thresholds:
  true_min: 0.7
  unclear_min: 0.4

labels:
  likely_true: "Likely True 🟢"
  unclear: "Unclear 🟡"
  likely_false: "Likely False 🔴"

use_supported_probability: true  # if true, p = P(SUPPORTED)

